server:
  port: 8010

spring:
  datasource:
    username: root
    password: 1234
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#      password: 123456
      channel-topic:
        short-link-stats: 'short-link:stats-stream'
        short-link-stats-group: 'short-link:stats-stream:only-group'

  mvc:
    view:
      prefix: /templates/
      suffix: .html

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  # 配置逻辑删除
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml

short-link:
  stats:
    locate:
      amap-key: aeeb6655501158929d6981a4290f5b69





















